---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-helm
  namespace: trial
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.nodeapp-helm: glob:master-*.*.*
spec:
  selector:
    matchLabels:
      app: nodeapp-helm
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapp-helm
    spec:
      containers:
      - name: nodeapp-helm
        image: {{ .Values.nodeapp.image }}
        ports:
        - containerPort: 3000
