apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluxtrial.fullname" . }}-2
  labels:
    {{- include "fluxtrial.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: tcptrial2
  selector:
    {{- include "fluxtrial.selectorLabels" . | nindent 4 }}
