---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: trial
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.nginx: glob:1.13.*
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
