---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  namespace: trial
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.nodeapp: glob:*
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: nirabhratapaswi/flux-trial-app:master
        ports:
        - containerPort: 80
