---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  namespace: trial
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.nodeapp: glob:master-*.*.*
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: nirabhratapaswi/flux-trial-app:master-0.3.0
        ports:
        - containerPort: 3000
