---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  namespace: trial
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.nodeapp: glob:master-*.*.*
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
<<<<<<< HEAD
        image: nirabhratapaswi/flux-trial-app:master-0.1.6
=======
        image: nirabhratapaswi/flux-trial-app:dev-0.2.0
>>>>>>> 9ae30e9843e6d5f0b53c4f1c5340f6dd1c14b9f2
        ports:
        - containerPort: 3000
