---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: trial
  namespace: trial
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:*
spec:
  releaseName: flux-trial
  forceUpgrade: true
  chart:
    git: https://github.com/nirabhratapaswi/fluxtrial
    ref: master
    path: charts/trial
  values:
    replicaCount: 1
    service:
      port: 84
