---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: trial
  namespace: trial
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:*
    filter.fluxcd.io/nodeapp: glob:dev-*.*.*
spec:
  releaseName: flux-trial
  targetNamespace: trial
  forceUpgrade: true
  resetValues: false
  chart:
    git: https://github.com/nirabhratapaswi/fluxtrial
    ref: master
    path: charts/trial
  values:
    replicaCount: 0
    service:
      port: 80
    nodeapp:
      image: nirabhratapaswi/flux-trial-app:master-0.1.3
